//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được phép trùng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_DuplicateAssetCode {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép trùng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_DuplicateCustomerCode {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khách hàng không được phép trùng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_DuplicateCustomerEmail {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateCustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại khách hàng không được phép trùng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_DuplicateCustomerPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateCustomerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_EmptyAssetCode {
            get {
                return ResourceManager.GetString("ErrorService_EmptyAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_EmptyAssetName {
            get {
                return ResourceManager.GetString("ErrorService_EmptyAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_EmptyCustomerCode {
            get {
                return ResourceManager.GetString("ErrorService_EmptyCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên khách hàng không thể bỏ trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_EmptyCustomerFullName {
            get {
                return ResourceManager.GetString("ErrorService_EmptyCustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại khách hàng không thể bỏ trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_EmptyCustomerPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorService_EmptyCustomerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA..
        /// </summary>
        public static string ErrorService_General {
            get {
                return ResourceManager.GetString("ErrorService_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id không tồn tại.
        /// </summary>
        public static string ErrorService_IdNotExist {
            get {
                return ResourceManager.GetString("ErrorService_IdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorService_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorService_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorService_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.
        /// </summary>
        public static string Regex_Email {
            get {
                return ResourceManager.GetString("Regex_Email", resourceCulture);
            }
        }
    }
}
